version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: ../eden-backend/eden  # Adjusted to the correct path
      dockerfile: Dockerfile
    command: celery -A eden worker --loglevel=info
    environment:
      - REDIS_HOST=redis
    volumes:
      - ../eden-backend/eden/:/code/
    depends_on:
      - redis

